# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - base_mlp_agg
  - _self_
  
data_config:
  _target_: face_plm.probes.data.AnkhLayerSpecificRegressionDataModule
  train_config: ${train_config}
  
train_config:
  gpu_num: 0
  max_epoch_number: 10
  warmup_epochs: 1

encoder_config:
  input_dim: 768
 
wandb_config:
  run_name: ankh-base-vit-tiny_multi_layer
  
min_layer: 0
max_layer: 3