# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - base_mlp_agg
  - _self_

data_config: 
  _target_: face_plm.probes.data.PLMEmbeddingRegressionDataModule
  train_config: ${train_config}
  model_name: "esmc_600m"
  aggregation: "min"
  
train_config:
  gpu_num: 1
  max_epoch_number: 10
  warmup_epochs: 1

encoder_config:
  input_dim: 1152

wandb_config:
  run_name: new_config_test


  