# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - vit_tiny_base_config
  - wandb_config: base_wandb
  - _self_

data_config: 
  _target_: face_plm.probes.data.PLMEmbeddingRegressionDataModule
  train_config: ${train_config}
  model_name: "prot_t5_xl_bfd"
  
train_config:
  gpu_num: 3

encoder_config:
  input_dim: 1024
  num_heads: 4

wandb_config:
  run_name: prot_t5_xl_bfd-vit_tiny


  