# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - vit_tiny_base_config
  - _self_

data_config: 
  _target_: adk_dl.data.PLMEmbeddingRegressionDataModule
  train_config: ${train_config}
  model_name: "ankh-large"
  
train_config:
  gpu_num: 2

encoder_config:
  input_dim: 1536

wandb_config:
  run_name: ankh_large-vit_tiny


  