# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - vit_tiny_base_config
  - _self_
  
data_config: 
  _target_: adk_dl.data.AnkhLayerSpecificRegressionDataModule
  train_config: ${train_config}
  
train_config:
  gpu_num: 1
  max_epoch_number: 200

encoder_config:
  input_dim: 768
 
wandb_config:
  run_name: ankh-base-vit-tiny  
  entity: kampmann_lab

min_layer: 13
max_layer: 20