# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - plm_mlp_base_config
  - _self_

data_config: 
  _target_: adk_dl.data.PLMEmbeddingRegressionDataModule
  train_config: ${train_config}
  model_name: "esm3-sm-open-v1"
  aggregation: "min"
  
train_config:
  gpu_num: 2

lr_config:
  final_value: 1e-8
  warmup_initial_value: 1e-7
  base_value: 1e-6

encoder_config:
  input_dim: 1536

wandb_config:
  run_name: esm3-sm-open-v1_mlp
  entity: kampmann_lab


  