# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - plm_mlp_base_config
  - _self_

data_config: 
  _target_: adk_dl.data.PLMEmbeddingRegressionDataModule
  train_config: ${train_config}
  model_name: "esmc_600m"
  aggregation: "max"
  
train_config:
  gpu_num: 1

encoder_config:
  input_dim: 1152

wandb_config:
  run_name: esmc_600m_mlp
  entity: kampmann_lab


  