# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - plm_mlp_base_config
  - _self_

data_config: 
  _target_: adk_dl.data.PLMEmbeddingRegressionDataModule
  train_config: ${train_config}
  model_name: "ProstT5"
  aggregation: "min"
  
train_config:
  gpu_num: 2

encoder_config:
  input_dim: 1024

wandb_config:
  run_name: ProstT5-mlp
  entity: kampmann_lab


  