# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - vit_tiny_base_config
  - _self_

data_config: 
  _target_: adk_dl.data.PLMEmbeddingRegressionDataModule
  train_config: ${train_config}
  model_name: "ProstT5"
  
train_config:
  gpu_num: 1

encoder_config:
  input_dim: 1024
  num_heads: 4

wandb_config:
  run_name: ProstT5-vit_tiny


  